<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GewogTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('gewogs')->insert([
            ['id' => 1, 'dzongkhag_id' => 1, 'name' => 'Chhoekhor' , 'created_by' => 1],
            ['id' => 2, 'dzongkhag_id' => 1, 'name' => 'Chhumig' , 'created_by' => 1],
            ['id' => 3, 'dzongkhag_id' => 1, 'name' => 'Tang' , 'created_by' => 1],
            ['id' => 4, 'dzongkhag_id' => 1, 'name' => 'Ura' , 'created_by' => 1],
            ['id' => 5, 'dzongkhag_id' => 2, 'name' => 'Bjagchhog' , 'created_by' => 1],
            ['id' => 6, 'dzongkhag_id' => 2, 'name' => 'Bongo' , 'created_by' => 1],
            ['id' => 7, 'dzongkhag_id' => 2, 'name' => 'Chapchha' , 'created_by' => 1],
            ['id' => 8, 'dzongkhag_id' => 2, 'name' => 'Darla' , 'created_by' => 1],
            ['id' => 9, 'dzongkhag_id' => 2, 'name' => 'Doongna' , 'created_by' => 1],
            ['id' => 10, 'dzongkhag_id' => 2, 'name' => 'Geling' , 'created_by' => 1],
            ['id' => 11, 'dzongkhag_id' => 2, 'name' => 'Getana' , 'created_by' => 1],
            ['id' => 12, 'dzongkhag_id' => 2, 'name' => 'Loggchina' , 'created_by' => 1],
            ['id' => 13, 'dzongkhag_id' => 2, 'name' => 'Maedtabkha' , 'created_by' => 1],
            ['id' => 14, 'dzongkhag_id' => 2, 'name' => 'Phuentshogling' , 'created_by' => 1],
            ['id' => 15, 'dzongkhag_id' => 2, 'name' => 'Samphelling (Bhalujora)' , 'created_by' => 1],
            ['id' => 16, 'dzongkhag_id' => 3, 'name' => 'Dorona' , 'created_by' => 1],
            ['id' => 17, 'dzongkhag_id' => 3, 'name' => 'Drukjeygang' , 'created_by' => 1],
            ['id' => 18, 'dzongkhag_id' => 3, 'name' => 'Gesarling' , 'created_by' => 1],
            ['id' => 19, 'dzongkhag_id' => 3, 'name' => 'Gozhi ' , 'created_by' => 1],
            ['id' => 20, 'dzongkhag_id' => 3, 'name' => 'Karna' , 'created_by' => 1],
            ['id' => 21, 'dzongkhag_id' => 3, 'name' => 'Karmaling (Deorali)' , 'created_by' => 1],
            ['id' => 22, 'dzongkhag_id' => 3, 'name' => 'Khebisa' , 'created_by' => 1],
            ['id' => 23, 'dzongkhag_id' => 3, 'name' => 'Largyab' , 'created_by' => 1],
            ['id' => 24, 'dzongkhag_id' => 3, 'name' => 'Lhamoi Dzingkha' , 'created_by' => 1],
            ['id' => 25, 'dzongkhag_id' => 3, 'name' => 'Nichula' , 'created_by' => 1],
            ['id' => 26, 'dzongkhag_id' => 3, 'name' => 'Tashiding' , 'created_by' => 1],
            ['id' => 27, 'dzongkhag_id' => 3, 'name' => 'Tsangkha ' , 'created_by' => 1],
            ['id' => 28, 'dzongkhag_id' => 3, 'name' => 'Tsenda-Gang ' , 'created_by' => 1],
            ['id' => 29, 'dzongkhag_id' => 3, 'name' => 'Tseza ' , 'created_by' => 1],
            ['id' => 30, 'dzongkhag_id' => 4, 'name' => 'Khamaed ' , 'created_by' => 1],
            ['id' => 31, 'dzongkhag_id' => 4, 'name' => 'Khatoed ' , 'created_by' => 1],
            ['id' => 32, 'dzongkhag_id' => 4, 'name' => 'Laya ' , 'created_by' => 1],
            ['id' => 33, 'dzongkhag_id' => 4, 'name' => 'Lunana ' , 'created_by' => 1],
            ['id' => 34, 'dzongkhag_id' => 5, 'name' => 'Bji ' , 'created_by' => 1],
            ['id' => 35, 'dzongkhag_id' => 5, 'name' => 'Uesu ' , 'created_by' => 1],
            ['id' => 36, 'dzongkhag_id' => 5, 'name' => 'Gakiling ' , 'created_by' => 1],
            ['id' => 37, 'dzongkhag_id' => 5, 'name' => 'Kar-tshog ' , 'created_by' => 1],
            ['id' => 38, 'dzongkhag_id' => 5, 'name' => 'Samar ' , 'created_by' => 1],
            ['id' => 39, 'dzongkhag_id' => 5, 'name' => 'Sangbay ' , 'created_by' => 1],
            ['id' => 40, 'dzongkhag_id' => 6, 'name' => 'Gangzur ' , 'created_by' => 1],
            ['id' => 41, 'dzongkhag_id' => 6, 'name' => 'Jarey ' , 'created_by' => 1],
            ['id' => 42, 'dzongkhag_id' => 6, 'name' => 'Khoma ' , 'created_by' => 1],
            ['id' => 43, 'dzongkhag_id' => 6, 'name' => 'Kurtoed ' , 'created_by' => 1],
            ['id' => 44, 'dzongkhag_id' => 6, 'name' => 'Maenbi ' , 'created_by' => 1],
            ['id' => 45, 'dzongkhag_id' => 6, 'name' => 'Maedtsho ' , 'created_by' => 1],
            ['id' => 46, 'dzongkhag_id' => 6, 'name' => 'Minjey ' , 'created_by' => 1],
            ['id' => 47, 'dzongkhag_id' => 6, 'name' => 'Tsaenkhar ' , 'created_by' => 1],
            ['id' => 48, 'dzongkhag_id' => 7, 'name' => 'Balam ' , 'created_by' => 1],
            ['id' => 49, 'dzongkhag_id' => 7, 'name' => 'Chhaling ' , 'created_by' => 1],
            ['id' => 50, 'dzongkhag_id' => 7, 'name' => 'Chagsakhar ' , 'created_by' => 1],
            ['id' => 51, 'dzongkhag_id' => 7, 'name' => 'Dramedtse ' , 'created_by' => 1],
            ['id' => 52, 'dzongkhag_id' => 7, 'name' => 'Drepoong ' , 'created_by' => 1],
            ['id' => 53, 'dzongkhag_id' => 7, 'name' => 'Gongdue ' , 'created_by' => 1],
            ['id' => 54, 'dzongkhag_id' => 7, 'name' => 'Jurmed ' , 'created_by' => 1],
            ['id' => 55, 'dzongkhag_id' => 7, 'name' => 'Kengkhar ' , 'created_by' => 1],
            ['id' => 56, 'dzongkhag_id' => 7, 'name' => 'Monggar ' , 'created_by' => 1],
            ['id' => 57, 'dzongkhag_id' => 7, 'name' => 'Na-Rang ' , 'created_by' => 1],
            ['id' => 58, 'dzongkhag_id' => 7, 'name' => 'Ngatshang ' , 'created_by' => 1],
            ['id' => 59, 'dzongkhag_id' => 7, 'name' => 'Saling ' , 'created_by' => 1],
            ['id' => 60, 'dzongkhag_id' => 7, 'name' => 'Shermuhoong ' , 'created_by' => 1],
            ['id' => 61, 'dzongkhag_id' => 7, 'name' => 'Silambi ' , 'created_by' => 1],
            ['id' => 62, 'dzongkhag_id' => 7, 'name' => 'Thang-Rong ' , 'created_by' => 1],
            ['id' => 63, 'dzongkhag_id' => 7, 'name' => 'Tsakaling ' , 'created_by' => 1],
            ['id' => 64, 'dzongkhag_id' => 7, 'name' => 'Tsamang ' , 'created_by' => 1],
            ['id' => 65, 'dzongkhag_id' => 8, 'name' => 'Dokar ' , 'created_by' => 1],
            ['id' => 66, 'dzongkhag_id' => 8, 'name' => 'Dopshar-ri ' , 'created_by' => 1],
            ['id' => 67, 'dzongkhag_id' => 8, 'name' => 'Doteng ' , 'created_by' => 1],
            ['id' => 68, 'dzongkhag_id' => 8, 'name' => 'Hoongrel ' , 'created_by' => 1],
            ['id' => 69, 'dzongkhag_id' => 8, 'name' => 'Lamgong ' , 'created_by' => 1],
            ['id' => 70, 'dzongkhag_id' => 8, 'name' => 'Loong-nyi ' , 'created_by' => 1],
            ['id' => 71, 'dzongkhag_id' => 8, 'name' => 'Nagya ' , 'created_by' => 1],
            ['id' => 72, 'dzongkhag_id' => 8, 'name' => 'Sharpa ' , 'created_by' => 1],
            ['id' => 73, 'dzongkhag_id' => 8, 'name' => 'Tsento ' , 'created_by' => 1],
            ['id' => 74, 'dzongkhag_id' => 8, 'name' => 'Wangchang ' , 'created_by' => 1],
            ['id' => 75, 'dzongkhag_id' => 9, 'name' => 'Chhoekhorling ' , 'created_by' => 1],
            ['id' => 76, 'dzongkhag_id' => 9, 'name' => 'Chhimoong ' , 'created_by' => 1],
            ['id' => 77, 'dzongkhag_id' => 9, 'name' => 'Chongshing ' , 'created_by' => 1],
            ['id' => 78, 'dzongkhag_id' => 9, 'name' => 'Dechhenling ' , 'created_by' => 1],
            ['id' => 79, 'dzongkhag_id' => 9, 'name' => 'Dungmaed ' , 'created_by' => 1],
            ['id' => 80, 'dzongkhag_id' => 9, 'name' => 'Khar ' , 'created_by' => 1],
            ['id' => 81, 'dzongkhag_id' => 9, 'name' => 'Nanong ' , 'created_by' => 1],
            ['id' => 82, 'dzongkhag_id' => 9, 'name' => 'Norboogang ' , 'created_by' => 1],
            ['id' => 83, 'dzongkhag_id' => 9, 'name' => 'Shumar ' , 'created_by' => 1],
            ['id' => 84, 'dzongkhag_id' => 9, 'name' => 'Yurung ' , 'created_by' => 1],
            ['id' => 85, 'dzongkhag_id' => 9, 'name' => 'Zobel ' , 'created_by' => 1],
            ['id' => 86, 'dzongkhag_id' => 10, 'name' => 'Barp ' , 'created_by' => 1],
            ['id' => 87, 'dzongkhag_id' => 10, 'name' => 'Chhubu ' , 'created_by' => 1],
            ['id' => 88, 'dzongkhag_id' => 10, 'name' => 'Dzomi ' , 'created_by' => 1],
            ['id' => 89, 'dzongkhag_id' => 10, 'name' => 'Goenshari ' , 'created_by' => 1],
            ['id' => 90, 'dzongkhag_id' => 10, 'name' => 'Guma ' , 'created_by' => 1],
            ['id' => 91, 'dzongkhag_id' => 10, 'name' => 'Kabisa ' , 'created_by' => 1],
            ['id' => 92, 'dzongkhag_id' => 10, 'name' => 'Lingmukha ' , 'created_by' => 1],
            ['id' => 93, 'dzongkhag_id' => 10, 'name' => 'Shelnga-Bjemi ' , 'created_by' => 1],
            ['id' => 94, 'dzongkhag_id' => 10, 'name' => 'Talog ' , 'created_by' => 1],
            ['id' => 95, 'dzongkhag_id' => 10, 'name' => 'Toedpaisa ' , 'created_by' => 1],
            ['id' => 96, 'dzongkhag_id' => 10, 'name' => 'Toedwang ' , 'created_by' => 1],
            ['id' => 97, 'dzongkhag_id' => 11, 'name' => 'Dewathang ' , 'created_by' => 1],
            ['id' => 98, 'dzongkhag_id' => 11, 'name' => 'Gomdar ' , 'created_by' => 1],
            ['id' => 99, 'dzongkhag_id' => 11, 'name' => 'Langchenphu ' , 'created_by' => 1],
            ['id' => 100, 'dzongkhag_id' => 11, 'name' => 'Lauri ' , 'created_by' => 1],
            ['id' => 101, 'dzongkhag_id' => 11, 'name' => 'Martshala ' , 'created_by' => 1],
            ['id' => 102, 'dzongkhag_id' => 11, 'name' => 'Orong ' , 'created_by' => 1],
            ['id' => 103, 'dzongkhag_id' => 11, 'name' => 'Pemathang ' , 'created_by' => 1],
            ['id' => 104, 'dzongkhag_id' => 11, 'name' => 'Phuentshogthang ' , 'created_by' => 1],
            ['id' => 105, 'dzongkhag_id' => 11, 'name' => 'Samrang ' , 'created_by' => 1],
            ['id' => 106, 'dzongkhag_id' => 11, 'name' => 'Serthig ' , 'created_by' => 1],
            ['id' => 107, 'dzongkhag_id' => 11, 'name' => 'Wangphu ' , 'created_by' => 1],
            ['id' => 108, 'dzongkhag_id' => 12, 'name' => 'Norgaygang (Bara)' , 'created_by' => 1],
            ['id' => 109, 'dzongkhag_id' => 12, 'name' => 'Pemaling (Biru)' , 'created_by' => 1],
            ['id' => 110, 'dzongkhag_id' => 12, 'name' => 'Sang-Ngag-Chhoeling (Chargharey)' , 'created_by' => 1],
            ['id' => 111, 'dzongkhag_id' => 12, 'name' => 'Doomtoed ' , 'created_by' => 1],
            ['id' => 112, 'dzongkhag_id' => 12, 'name' => 'Duenchhukha ' , 'created_by' => 1],
            ['id' => 113, 'dzongkhag_id' => 12, 'name' => 'Dophuchen (Dorokha)' , 'created_by' => 1],
            ['id' => 114, 'dzongkhag_id' => 12, 'name' => 'Namgyalchhoeling ' , 'created_by' => 1],
            ['id' => 115, 'dzongkhag_id' => 12, 'name' => 'Phuentshogpelri (Pugli)' , 'created_by' => 1],
            ['id' => 116, 'dzongkhag_id' => 12, 'name' => 'Samtse ' , 'created_by' => 1],
            ['id' => 117, 'dzongkhag_id' => 12, 'name' => 'Tashichhoeling (Sipsu)' , 'created_by' => 1],
            ['id' => 118, 'dzongkhag_id' => 12, 'name' => 'Tading ' , 'created_by' => 1],
            ['id' => 119, 'dzongkhag_id' => 12, 'name' => 'Tendruk ' , 'created_by' => 1],
            ['id' => 120, 'dzongkhag_id' => 12, 'name' => 'Ugyentse (Nainital)' , 'created_by' => 1],
            ['id' => 121, 'dzongkhag_id' => 12, 'name' => 'Yoeseltse (Ghumauney)' , 'created_by' => 1],
            ['id' => 122, 'dzongkhag_id' => 12, 'name' => 'Norboogang' , 'created_by' => 1],
            ['id' => 123, 'dzongkhag_id' => 13, 'name' => 'Chhuzanggang ' , 'created_by' => 1],
            ['id' => 124, 'dzongkhag_id' => 13, 'name' => 'Chhudzom (Dovan)' , 'created_by' => 1],
            ['id' => 125, 'dzongkhag_id' => 13, 'name' => 'Dekiling ' , 'created_by' => 1],
            ['id' => 126, 'dzongkhag_id' => 13, 'name' => 'Gakiling (Hilley)' , 'created_by' => 1],
            ['id' => 127, 'dzongkhag_id' => 13, 'name' => 'Gelegphu ' , 'created_by' => 1],
            ['id' => 128, 'dzongkhag_id' => 13, 'name' => 'Jigme Chhoeling ' , 'created_by' => 1],
            ['id' => 129, 'dzongkhag_id' => 13, 'name' => 'Samtenling (Bhur)' , 'created_by' => 1],
            ['id' => 130, 'dzongkhag_id' => 13, 'name' => 'Senggey ' , 'created_by' => 1],
            ['id' => 131, 'dzongkhag_id' => 13, 'name' => 'Serzhong ' , 'created_by' => 1],
            ['id' => 132, 'dzongkhag_id' => 13, 'name' => 'Shompangkha ' , 'created_by' => 1],
            ['id' => 133, 'dzongkhag_id' => 13, 'name' => 'Tareythang (Taklai)' , 'created_by' => 1],
            ['id' => 134, 'dzongkhag_id' => 13, 'name' => 'Umling ' , 'created_by' => 1],
            ['id' => 135, 'dzongkhag_id' => 14, 'name' => 'Chang ' , 'created_by' => 1],
            ['id' => 136, 'dzongkhag_id' => 14, 'name' => 'Lingzhi ' , 'created_by' => 1],
            ['id' => 137, 'dzongkhag_id' => 14, 'name' => 'Soe ' , 'created_by' => 1],
            ['id' => 138, 'dzongkhag_id' => 14, 'name' => 'Ge-nyen ' , 'created_by' => 1],
            ['id' => 139, 'dzongkhag_id' => 14, 'name' => 'Kawang' , 'created_by' => 1],
            ['id' => 140, 'dzongkhag_id' => 14, 'name' => 'Maedwang ' , 'created_by' => 1],
            ['id' => 141, 'dzongkhag_id' => 14, 'name' => 'Naro ' , 'created_by' => 1],
            ['id' => 142, 'dzongkhag_id' => 14, 'name' => 'Darkarla ' , 'created_by' => 1],
            ['id' => 143, 'dzongkhag_id' => 15, 'name' => 'Bartsham ' , 'created_by' => 1],
            ['id' => 144, 'dzongkhag_id' => 15, 'name' => 'Bidoong ' , 'created_by' => 1],
            ['id' => 145, 'dzongkhag_id' => 15, 'name' => 'Kanglung ' , 'created_by' => 1],
            ['id' => 146, 'dzongkhag_id' => 15, 'name' => 'Kangpar ' , 'created_by' => 1],
            ['id' => 147, 'dzongkhag_id' => 15, 'name' => 'Khaling ' , 'created_by' => 1],
            ['id' => 148, 'dzongkhag_id' => 15, 'name' => 'Lumang ' , 'created_by' => 1],
            ['id' => 149, 'dzongkhag_id' => 15, 'name' => 'Merag ' , 'created_by' => 1],
            ['id' => 150, 'dzongkhag_id' => 15, 'name' => 'Phongmed ' , 'created_by' => 1],
            ['id' => 151, 'dzongkhag_id' => 15, 'name' => 'Radhi ' , 'created_by' => 1],
            ['id' => 152, 'dzongkhag_id' => 15, 'name' => 'Sagteng ' , 'created_by' => 1],
            ['id' => 153, 'dzongkhag_id' => 15, 'name' => 'Samkhar ' , 'created_by' => 1],
            ['id' => 154, 'dzongkhag_id' => 15, 'name' => 'Shongphu ' , 'created_by' => 1],
            ['id' => 155, 'dzongkhag_id' => 15, 'name' => 'Thrimshing ' , 'created_by' => 1],
            ['id' => 156, 'dzongkhag_id' => 15, 'name' => 'Udzorong ' , 'created_by' => 1],
            ['id' => 157, 'dzongkhag_id' => 15, 'name' => 'Yangnyer ' , 'created_by' => 1],
            ['id' => 158, 'dzongkhag_id' => 16, 'name' => 'Boomdeling ' , 'created_by' => 1],
            ['id' => 159, 'dzongkhag_id' => 16, 'name' => 'Jamkhar ' , 'created_by' => 1],
            ['id' => 160, 'dzongkhag_id' => 16, 'name' => 'Khamdang ' , 'created_by' => 1],
            ['id' => 161, 'dzongkhag_id' => 16, 'name' => 'Ramjar ' , 'created_by' => 1],
            ['id' => 162, 'dzongkhag_id' => 16, 'name' => 'Toedtsho ' , 'created_by' => 1],
            ['id' => 163, 'dzongkhag_id' => 16, 'name' => 'Tongmajangsa ' , 'created_by' => 1],
            ['id' => 164, 'dzongkhag_id' => 16, 'name' => 'Yangtse ' , 'created_by' => 1],
            ['id' => 165, 'dzongkhag_id' => 16, 'name' => 'Yalang ' , 'created_by' => 1],
            ['id' => 166, 'dzongkhag_id' => 17, 'name' => 'Draagteng ' , 'created_by' => 1],
            ['id' => 167, 'dzongkhag_id' => 17, 'name' => 'Korphu ' , 'created_by' => 1],
            ['id' => 168, 'dzongkhag_id' => 17, 'name' => 'Langthil ' , 'created_by' => 1],
            ['id' => 169, 'dzongkhag_id' => 17, 'name' => 'Nubi ' , 'created_by' => 1],
            ['id' => 170, 'dzongkhag_id' => 17, 'name' => 'Tangsibji ' , 'created_by' => 1],
            ['id' => 171, 'dzongkhag_id' => 18, 'name' => 'Barshong ' , 'created_by' => 1],
            ['id' => 172, 'dzongkhag_id' => 18, 'name' => 'Doonglagang ' , 'created_by' => 1],
            ['id' => 173, 'dzongkhag_id' => 18, 'name' => 'Gosarling ' , 'created_by' => 1],
            ['id' => 174, 'dzongkhag_id' => 18, 'name' => 'Kilkhorthang ' , 'created_by' => 1],
            ['id' => 175, 'dzongkhag_id' => 18, 'name' => 'Mendrelgang ' , 'created_by' => 1],
            ['id' => 176, 'dzongkhag_id' => 18, 'name' => 'Patshaling (Beteni)' , 'created_by' => 1],
            ['id' => 177, 'dzongkhag_id' => 18, 'name' => 'Pungtenchhu ' , 'created_by' => 1],
            ['id' => 178, 'dzongkhag_id' => 18, 'name' => 'Rangthangling ' , 'created_by' => 1],
            ['id' => 179, 'dzongkhag_id' => 18, 'name' => 'Semjong ' , 'created_by' => 1],
            ['id' => 180, 'dzongkhag_id' => 18, 'name' => 'Sergithang (Patala)' , 'created_by' => 1],
            ['id' => 181, 'dzongkhag_id' => 18, 'name' => 'Tsholingkhar ' , 'created_by' => 1],
            ['id' => 182, 'dzongkhag_id' => 18, 'name' => 'Tsirang Toed ' , 'created_by' => 1],
            ['id' => 183, 'dzongkhag_id' => 19, 'name' => 'Athang ' , 'created_by' => 1],
            ['id' => 184, 'dzongkhag_id' => 19, 'name' => 'Bjenag ' , 'created_by' => 1],
            ['id' => 185, 'dzongkhag_id' => 19, 'name' => 'Darkar ' , 'created_by' => 1],
            ['id' => 186, 'dzongkhag_id' => 19, 'name' => 'Dangchhu ' , 'created_by' => 1],
            ['id' => 187, 'dzongkhag_id' => 19, 'name' => 'Gangteng ' , 'created_by' => 1],
            ['id' => 188, 'dzongkhag_id' => 19, 'name' => 'Kazhi ' , 'created_by' => 1],
            ['id' => 189, 'dzongkhag_id' => 19, 'name' => 'Gase Tshogongm ' , 'created_by' => 1],
            ['id' => 190, 'dzongkhag_id' => 19, 'name' => 'Gase Tshowogm ' , 'created_by' => 1],
            ['id' => 191, 'dzongkhag_id' => 19, 'name' => 'Nyishog' , 'created_by' => 1],
            ['id' => 192, 'dzongkhag_id' => 19, 'name' => 'Nahi ' , 'created_by' => 1],
            ['id' => 193, 'dzongkhag_id' => 19, 'name' => 'Phangyuel ' , 'created_by' => 1],
            ['id' => 194, 'dzongkhag_id' => 19, 'name' => 'Saephu ' , 'created_by' => 1],
            ['id' => 195, 'dzongkhag_id' => 19, 'name' => 'Phobji ' , 'created_by' => 1],
            ['id' => 196, 'dzongkhag_id' => 19, 'name' => 'Ruebisa ' , 'created_by' => 1],
            ['id' => 197, 'dzongkhag_id' => 19, 'name' => 'Thedtsho ' , 'created_by' => 1],
            ['id' => 198, 'dzongkhag_id' => 20, 'name' => 'Bardo ' , 'created_by' => 1],
            ['id' => 199, 'dzongkhag_id' => 20, 'name' => 'Bjoka ' , 'created_by' => 1],
            ['id' => 200, 'dzongkhag_id' => 20, 'name' => 'Goshing ' , 'created_by' => 1],
            ['id' => 201, 'dzongkhag_id' => 20, 'name' => 'Nangkor ' , 'created_by' => 1],
            ['id' => 202, 'dzongkhag_id' => 20, 'name' => 'Ngangla ' , 'created_by' => 1],
            ['id' => 203, 'dzongkhag_id' => 20, 'name' => 'Phangkhar ' , 'created_by' => 1],
            ['id' => 204, 'dzongkhag_id' => 20, 'name' => 'Shingkhar ' , 'created_by' => 1],
            ['id' => 205, 'dzongkhag_id' => 20, 'name' => 'Trong ' , 'created_by' => 1],
            ['id' => 206, 'dzongkhag_id' => 1, 'name' => 'Bumthang Thromde' , 'created_by' => 1],
            ['id' => 207, 'dzongkhag_id' => 2, 'name' => 'Phuentshogling Thromde' , 'created_by' => 1],
            ['id' => 208, 'dzongkhag_id' => 3, 'name' => 'Daga Thromde' , 'created_by' => 1],
            ['id' => 209, 'dzongkhag_id' => 4, 'name' => 'Gasa Thromde' , 'created_by' => 1],
            ['id' => 210, 'dzongkhag_id' => 5, 'name' => 'Haa Thromde' , 'created_by' => 1],
            ['id' => 211, 'dzongkhag_id' => 6, 'name' => 'Lhuentse Thromde' , 'created_by' => 1],
            ['id' => 212, 'dzongkhag_id' => 7, 'name' => 'Monggar Thromde' , 'created_by' => 1],
            ['id' => 213, 'dzongkhag_id' => 8, 'name' => 'Paro Thromde' , 'created_by' => 1],
            ['id' => 214, 'dzongkhag_id' => 9, 'name' => 'Denchi Thromde' , 'created_by' => 1],
            ['id' => 215, 'dzongkhag_id' => 10, 'name' => 'Khuruthang Thromde' , 'created_by' => 1],
            ['id' => 216, 'dzongkhag_id' => 11, 'name' => 'Samdrup Jongkhar Thromde' , 'created_by' => 1],
            ['id' => 217, 'dzongkhag_id' => 12, 'name' => 'Samtse Thromde' , 'created_by' => 1],
            ['id' => 218, 'dzongkhag_id' => 13, 'name' => 'Gelegphu Thromde' , 'created_by' => 1],
            ['id' => 219, 'dzongkhag_id' => 14, 'name' => 'Thimphu Thromde' , 'created_by' => 1],
            ['id' => 220, 'dzongkhag_id' => 15, 'name' => 'Trashigang Thromde' , 'created_by' => 1],
            ['id' => 221, 'dzongkhag_id' => 16, 'name' => 'Trashi Yangtse Thromde' , 'created_by' => 1],
            ['id' => 222, 'dzongkhag_id' => 17, 'name' => 'Trongsa Thromde' , 'created_by' => 1],
            ['id' => 223, 'dzongkhag_id' => 18, 'name' => 'Tsirang Thromde' , 'created_by' => 1],
            ['id' => 224, 'dzongkhag_id' => 19, 'name' => 'Bajo Thromde' , 'created_by' => 1],
            ['id' => 225, 'dzongkhag_id' => 20, 'name' => 'Zhemgang Thromde' , 'created_by' => 1]

		 ]);
    }
}
